<!-- Report Type Field -->
<div class="col-sm-12">
    {!! Form::label('report_type', 'Report Type:') !!}
    <p>{{ $report->report_type }}</p>
</div>

<!-- Generated By Field -->
<div class="col-sm-12">
    {!! Form::label('generated_by', 'Generated By:') !!}
    <p>{{ $report->generated_by }}</p>
</div>

<!-- Date Field -->
<div class="col-sm-12">
    {!! Form::label('date', 'Date:') !!}
    <p>{{ $report->date }}</p>
</div>

<!-- Summary Field -->
<div class="col-sm-12">
    {!! Form::label('summary', 'Summary:') !!}
    <p>{{ $report->summary }}</p>
</div>

